# Generated by Django 3.0.1 on 2020-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191231_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status_text',
            field=models.CharField(blank=True, default='Hello', max_length=50, null=True),
        ),
    ]
